//$file${./ArenaControlle~::AnalogInput.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ArenaController.qm
// File:  ${./ArenaControlle~::AnalogInput.cpp}
//
// This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./ArenaControlle~::AnalogInput.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "AnalogInput.hpp"


using namespace QP;

//============================================================================
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared::AnalogInput_getInstance} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AC {

//${Shared::AnalogInput_getInstance} .........................................
QP::QHsm * AnalogInput_getInstance() {
    return &AnalogInput::instance;
}

} // namespace AC
//$enddef${Shared::AnalogInput_getInstance} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//============================================================================
// generate definition of the HSM
//$define${AOs::AnalogInput} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AC {

//${AOs::AnalogInput} ........................................................
AnalogInput AnalogInput::instance;

//${AOs::AnalogInput::AnalogInput} ...........................................
AnalogInput::AnalogInput()
  : QHsm(&initial)
{}

//${AOs::AnalogInput::SM} ....................................................
Q_STATE_DEF(AnalogInput, initial) {
    //${AOs::AnalogInput::SM::initial}
    FSP::AnalogInput_initialize(this, e);

    QS_FUN_DICTIONARY(&AnalogInput::Uninitialized);
    QS_FUN_DICTIONARY(&AnalogInput::Initialized);

    return tran(&Uninitialized);
}

//${AOs::AnalogInput::SM::Uninitialized} .....................................
Q_STATE_DEF(AnalogInput, Uninitialized) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AnalogInput::SM::Uninitialized::ANALOG_INPUT_INITIALIZED}
        case ANALOG_INPUT_INITIALIZED_SIG: {
            status_ = tran(&Initialized);
            break;
        }
        //${AOs::AnalogInput::SM::Uninitialized::INITIALIZE_ANALOG_INPUT}
        case INITIALIZE_ANALOG_INPUT_SIG: {
            FSP::AnalogInput_initializeInput(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::AnalogInput::SM::Initialized} .......................................
Q_STATE_DEF(AnalogInput, Initialized) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AnalogInput::SM::Initialized}
        case Q_ENTRY_SIG: {
            FSP::AnalogInput_enterInitialized(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AnalogInput::SM::Initialized::GET_ANALOG_INPUT}
        case GET_ANALOG_INPUT_SIG: {
            FSP::AnalogInput_getInput(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

} // namespace AC
//$enddef${AOs::AnalogInput} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
