//$file${./ArenaControlle~::Analog.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ArenaController.qm
// File:  ${./ArenaControlle~::Analog.cpp}
//
// This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./ArenaControlle~::Analog.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "Analog.hpp"


using namespace QP;

//============================================================================
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared::Analog_getInstance} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AC {

//${Shared::Analog_getInstance} ..............................................
QP::QHsm * Analog_getInstance() {
    return &Analog::instance;
}

} // namespace AC
//$enddef${Shared::Analog_getInstance} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//============================================================================
// generate definition of the AO
//$define${AOs::Analog} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AC {

//${AOs::Analog} .............................................................
Analog Analog::instance;

//${AOs::Analog::Analog} .....................................................
Analog::Analog()
  : QHsm(&initial)
{}

//${AOs::Analog::SM} .........................................................
Q_STATE_DEF(Analog, initial) {
    //${AOs::Analog::SM::initial}
    FSP::Analog_initialize(this, e);

    QS_FUN_DICTIONARY(&Analog::Uninitialized);
    QS_FUN_DICTIONARY(&Analog::Initialized);

    return tran(&Uninitialized);
}

//${AOs::Analog::SM::Uninitialized} ..........................................
Q_STATE_DEF(Analog, Uninitialized) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Analog::SM::Uninitialized::ANALOG_INITIALIZED}
        case ANALOG_INITIALIZED_SIG: {
            status_ = tran(&Initialized);
            break;
        }
        //${AOs::Analog::SM::Uninitialized::INITIALIZE_ANALOG}
        case INITIALIZE_ANALOG_SIG: {
            FSP::Analog_initializeOutput(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Analog::SM::Initialized} ............................................
Q_STATE_DEF(Analog, Initialized) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Analog::SM::Initialized}
        case Q_ENTRY_SIG: {
            FSP::Analog_enterInitialized(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Analog::SM::Initialized::SET_ANALOG_OUTPUT}
        case SET_ANALOG_OUTPUT_SIG: {
            FSP::Analog_setOutput(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

} // namespace AC
//$enddef${AOs::Analog} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
