//.$file${./ArenaControlle~::ArenaController.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ArenaController.qm
// File:  ${./ArenaControlle~::ArenaController.cpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${./ArenaControlle~::ArenaController.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^
#include "ArenaController.hpp"  // ArenaController application interface

using namespace QP;

namespace AC {

//............................................................................
void setup() {

    QF::init(); // initialize the framework
    BSP::init(); // initialize the BSP

    // init publish-subscribe
    static QSubscrList subscrSto[AC::MAX_PUB_SIG];
    QF::psInit(subscrSto, Q_DIM(subscrSto));

   // statically allocate event queues for the AOs and start them...
    static QEvt const *arena_controller_queueSto[10];
    AC::AO_ArenaController->start(1U, // priority
        arena_controller_queueSto, Q_DIM(arena_controller_queueSto),
        (void *)0, 0U); // no stack
    //...
}

//............................................................................
void loop() {
    QF::run(); // run the QF/C++ framework
}

} // namespace AC

//============================================================================
// generate definitions of all AO classes (state machines)...
//.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//. Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${AOs::ArenaController} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AC {

//.${AOs::ArenaController} ...................................................
ArenaController ArenaController::instance;
//.${AOs::ArenaController::ArenaController} ..................................
ArenaController::ArenaController()
: QActive(Q_STATE_CAST(&ArenaController::initial)),
    command_time_evt_(this, COMMAND_TIMEOUT_SIG, 0U)
{}

//.${AOs::ArenaController::SM} ...............................................
Q_STATE_DEF(ArenaController, initial) {
    //.${AOs::ArenaController::SM::initial}
    (void)e; // suppress the compiler warning about unused parameter

    //QS_OBJ_DICTIONARY(&ArenaController::instance);

    //QS_SIG_DICTIONARY(RESET_SIG, nullptr); // global signals
    //QS_SIG_DICTIONARY(ALL_ON_SIG, nullptr);
    //QS_SIG_DICTIONARY(ALL_OFF_SIG, nullptr);

    //subscribe(RESET_SIG);
    subscribe(ALL_ON_SIG);
    subscribe(ALL_OFF_SIG);
    return tran(&DisplayOff);
}
//.${AOs::ArenaController::SM::ArenaOn} ......................................
Q_STATE_DEF(ArenaController, ArenaOn) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::ArenaController::SM::ArenaOn}
        case Q_ENTRY_SIG: {
            command_time_evt_.armX(BSP::TICKS_PER_SEC/2, BSP::TICKS_PER_SEC/2);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::ArenaController::SM::ArenaOn}
        case Q_EXIT_SIG: {
            command_time_evt_.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::ArenaController::SM::ArenaOn::RESET}
        case RESET_SIG: {
            status_ = tran(&ArenaOn);
            break;
        }
        //.${AOs::ArenaController::SM::ArenaOn::COMMAND_TIMEOUT}
        case COMMAND_TIMEOUT_SIG: {
            BSP::pollCommand();
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::ArenaController::SM::ArenaOn::ALL_OFF}
        case ALL_OFF_SIG: {
            status_ = tran(&DisplayOff);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.${AOs::ArenaController::SM::ArenaOn::DisplayOn} ...........................
Q_STATE_DEF(ArenaController, DisplayOn) {
    QP::QState status_;
    switch (e->sig) {
        default: {
            status_ = super(&ArenaOn);
            break;
        }
    }
    return status_;
}
//.${AOs::ArenaController::SM::ArenaOn::DisplayOn::AllOn} ....................
Q_STATE_DEF(ArenaController, AllOn) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::ArenaController::SM::ArenaOn::DisplayOn::AllOn}
        case Q_ENTRY_SIG: {
            BSP::ledOn();
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&DisplayOn);
            break;
        }
    }
    return status_;
}
//.${AOs::ArenaController::SM::ArenaOn::DisplayOff} ..........................
Q_STATE_DEF(ArenaController, DisplayOff) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::ArenaController::SM::ArenaOn::DisplayOff}
        case Q_ENTRY_SIG: {
            BSP::ledOff();
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::ArenaController::SM::ArenaOn::DisplayOff::ALL_ON}
        case ALL_ON_SIG: {
            status_ = tran(&AllOn);
            break;
        }
        default: {
            status_ = super(&ArenaOn);
            break;
        }
    }
    return status_;
}

} // namespace AC
//.$enddef${AOs::ArenaController} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//...

//============================================================================
// generate definitions of all AO opaque pointers...
//.$define${AOs::AO_ArenaController} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AC {

//.${AOs::AO_ArenaController} ................................................
QP::QActive * const AO_ArenaController = &ArenaController::instance;

} // namespace AC
//.$enddef${AOs::AO_ArenaController} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//...
