//.$file${.::arena_controller.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ArenaController.qm
// File:  ${.::arena_controller.hpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${.::arena_controller.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef ARENA_CONTROLLER_HPP
#define ARENA_CONTROLLER_HPP

enum ArenaControllerSignals {
    COMMAND_TIMEOUT_SIG = QP::Q_USER_SIG,
    RESET_SIG,
    ALL_ON_SIG,     // published by BSP to display all panels on
    ALL_OFF_SIG,    // published by BSP to display all panels off
    MAX_PUB_SIG,    // the last published signal
    MAX_SIG         // the last signal
};

// genearate declarations of all opaque AO pointers
//.$declare${AOs::AO_ArenaController} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
extern QP::QActive * const AO_ArenaController;
//.$enddecl${AOs::AO_ArenaController} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//...

#endif // ARENA_CONTROLLER_HPP
