//$file${.::Card.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ArenaController.qm
// File:  ${.::Card.hpp}
//
// This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Card.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef CARD_HPP
#define CARD_HPP

#include "Shared.hpp"
#include "Events.hpp"
#include "fsp.hpp"


//============================================================================
// generate declaration of the hsm
//$declare${AOs::Card} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AC {

//${AOs::Card} ...............................................................
class Card : public QP::QHsm {
public:
    static Card instance;
    std::uint16_t pattern_index_;
    std::uint64_t file_size_;

public:
    Card();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(Initialized);
    Q_STATE_DECL(WaitingToFindCard);
    Q_STATE_DECL(FindingCard);
    Q_STATE_DECL(FileOpened);
    Q_STATE_DECL(CheckingFile);
    Q_STATE_DECL(CheckingPattern);
    Q_STATE_DECL(DisplayingPattern);
    Q_STATE_DECL(WaitingToFindPattern);
    Q_STATE_DECL(OpeningDirectory);
}; // class Card

} // namespace AC
//$enddecl${AOs::Card} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
